copy image\arms.pdf en\image\
copy line_graphs\robot_links.pdf en\image\
copy line_graphs\view-via-z.pdf en\image\
copy line_graphs\view-via-xy.pdf en\image\
copy line_graphs\robot_box_io_plugin.pdf en\image\
copy image\35.pdf en\image\
copy line_graphs\install_direction_up.pdf en\image\
copy line_graphs\install_direction_down.pdf en\image\
copy line_graphs\install_direction_side.pdf en\image\
copy line_graphs\bottom_surface.pdf en\image\
copy line_graphs\flange_side_view.pdf en\image\
copy line_graphs\flange_face_view.pdf en\image\
copy line_graphs\flange_top_view.pdf en\image\
copy line_graphs\effective_payload.pdf en\image\
copy line_graphs\robot_control_box_back.pdf en\image\
copy image\network-1.pdf en\image\
copy image\network-2.pdf en\image\
copy screen\2-4.png en\image\
copy screen\2-5.png en\image\
copy screen\2-6.png en\image\
copy screen\2-7.png en\image\
copy screen\2-8.png en\image\
copy screen\2-9.png en\image\
copy shots\home.pdf en\image\
copy screen\2-11-t.jpg en\image\
copy screen\2-12-1.png en\image\
copy screen\2-12.png en\image\
copy screen\2-13.png en\image\
copy screen\2-14.png en\image\
copy screen\2-15.png en\image\
copy screen\2-16.png en\image\
copy image\6.pdf en\image\
copy screen\2-18.png en\image\
copy shots\timeline_editor.pdf en\image\
copy shots\code_editor.pdf en\image\
copy screen\3-3.png en\image\
copy screen\3-4.png en\image\
copy screen\3-5.png en\image\
copy screen\3-6.png en\image\
copy image\15.pdf en\image\
copy shots\fine_tuning_cartesian.pdf en\image\
copy line_graphs\fine_tuning_coordinate.pdf en\image\
copy shots\fine_tuning_joint.pdf en\image\
copy screen\3-11.png en\image\
copy screen\3-12.png en\image\
copy screen\3-13.png en\image\
copy screen\3-14.png en\image\
copy screen\3-15.png en\image\
copy line_graphs\shoulder_btn.pdf en\image\
copy shots\position_check.pdf en\image\
copy shots\batch_edit.pdf en\image\
copy shots\batch_adjust_positions.pdf en\image\
copy screen\3-19.png en\image\
copy screen\3-20.png en\image\
copy screen\3-21.png en\image\
copy line_graphs\flange_buttons.pdf en\image\
copy screen\3-24.png en\image\
copy screen\3-25.png en\image\
copy screen\3-26-1.png en\image\
copy screen\3-26-2.png en\image\
copy screen\3-27.png en\image\
copy screen\safe.png en\image\
copy screen\3-28.png en\image\
copy screen\3-29.png en\image\
